## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Dr. RT"
copyright = "{year}"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://rachtorr.github.io"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
# googleAnalytics = "G-XXXXXXXXXX"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Dr. RT"
  logo = "images/outdoorpic.jpg"
  favicon = true

[Params.social]
  github = "https://github.com/rachtorr/"
  email = "rachel.torres@humboldt.edu"
  instagram = "https://instagram.com"
  linkedin = "https://linkedin.com/in/rachtorr815"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]
